#!/bin/sh

case $1 in
    "debug")    st -e gdb -q -ex "target remote localhost:1234" &
                qemu-system-x86_64 -s -S os.bin
                ;;
    *)          qemu-system-x86_64 -drive format=raw,file="os.bin",index=0 -m 128M
                ;;
esac
